#!/usr/bin/env node
/**
 * Post-build step for the HOST build flow (`npm run build`).
 *
 * Angular's esbuild builder CLEANS the output path on every build, so two
 * artifacts that are NOT part of `ng build`'s output would be lost or stale
 * when the dist is volume-mounted into the frontend container
 * (infra/docker-compose.override.yml). This script restores both:
 *
 * 1. `assets/version.json` — the version-check toast polls this file
 *    (`VersionCheckService`, `VERSION_URL = '/assets/version.json'`). The
 *    source placeholder (`src/assets/version.json`) is static, so a host
 *    build would never change it and the "new version" banner never fires.
 *    Here it is rewritten with the build's UTC timestamp, matching the
 *    format the Dockerfile used to stamp (`YYYY-MM-DDTHH:MM:SS.000Z`).
 *
 * 2. `runtime-config.js` — the Syncfusion license file loaded by
 *    `src/index.html` (`<script src="/runtime-config.js">`) and read by
 *    `src/app/core/config/runtime-config.ts`. In the container it is
 *    generated by `docker-entrypoint.sh` from `SYNCFUSION_LICENSE_KEY`,
 *    written INSIDE the mounted dist — so `ng build` deletes it and the
 *    license would be lost. Two phases (wired via `prebuild` + `build` in
 *    package.json):
 *
 *    --capture (prebuild, BEFORE ng build wipes dist):
 *      if the CURRENT dist/runtime-config.js carries a non-empty license
 *      key (the one the container entrypoint injected on the last start),
 *      save it to a gitignored temp file.
 *
 *    restore (post ng build, in the build script):
 *      priority — (a) SYNCFUSION_LICENSE_KEY env → generate the file
 *      (mirrors docker-entrypoint.sh; explicit host-side control);
 *      (b) the --capture temp file → copy it back (zero-config: rebuilds
 *      keep the working license without a container restart);
 *      (c) `public/runtime-config.js` placeholder (empty key) → copy.
 *
 * The dist path `dist/frontend/browser` must match Angular's default
 * outputPath for the `frontend` project — if `outputPath` in angular.json
 * ever changes, this script fails loudly instead of silently writing
 * nowhere.
 */
import { copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const FRONTEND_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DIST_ROOT = resolve(FRONTEND_ROOT, 'dist/frontend/browser');
const DIST_CONFIG = resolve(DIST_ROOT, 'runtime-config.js');
const PUBLIC_CONFIG = resolve(FRONTEND_ROOT, 'public/runtime-config.js');
// Gitignored (vive en node_modules, que ya lo está) — sobrevive al clean de
// dist pero no entra al repo ni a la imagen.
const CAPTURE_FILE = resolve(FRONTEND_ROOT, 'node_modules/.cache/hd-post-build-runtime-config.js');

function fail(message) {
  console.error(`[post-build] ERROR: ${message}`);
  process.exit(1);
}

// ── Fase --capture (prebuild: el dist AÚN tiene lo que inyectó el container) ──
if (process.argv.includes('--capture')) {
  if (existsSync(DIST_CONFIG)) {
    const body = readFileSync(DIST_CONFIG, 'utf8');
    // Solo captura si hay una clave real (no el placeholder vacío). Ojo: el
    // key del objeto JS va SIN comillas (`{ syncfusionLicenseKey: "..." }`).
    if (/\bsyncfusionLicenseKey\s*:\s*"([^"]+)"/.test(body)) {
      mkdirSync(dirname(CAPTURE_FILE), { recursive: true });
      writeFileSync(CAPTURE_FILE, body);
      console.log('[post-build] --capture: runtime-config.js con clave real guardado (prebuild)');
    } else {
      // Sin clave real en el dist → descarta capturas obsoletas (p. ej. de un
      // build anterior que falló y nunca restauró) para no resucitar claves
      // desactualizadas en el próximo restore.
      rmSync(CAPTURE_FILE, { force: true });
    }
  } else {
    rmSync(CAPTURE_FILE, { force: true });
  }
  process.exit(0);
}

// ── Fase restore (tras `ng build`, dentro del script build) ────────────────
if (!existsSync(DIST_ROOT)) {
  fail(`no existe ${DIST_ROOT}. ¿Falló \`ng build\` o cambió el outputPath de angular.json?`);
}

// 1) version.json con timestamp fresco del build.
const build = new Date().toISOString().replace(/\.\d{3}Z$/, '.000Z');
const versionPath = resolve(DIST_ROOT, 'assets/version.json');
mkdirSync(dirname(versionPath), { recursive: true });
writeFileSync(versionPath, `${JSON.stringify({ build })}\n`);
console.log(`[post-build] version.json -> ${versionPath} (build ${build})`);

// 2) runtime-config.js (licencia Syncfusion) al raíz del dist.
function escapeJsString(value) {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

const envLicenseKey = (process.env.SYNCFUSION_LICENSE_KEY ?? '').trim();

if (envLicenseKey) {
  // (a) Env explícito → genera el archivo (mismo shape que docker-entrypoint.sh).
  const body = `window.__HOTELDATA_CONFIG__ = { syncfusionLicenseKey: "${escapeJsString(envLicenseKey)}" };`;
  writeFileSync(DIST_CONFIG, `${body}\n`);
  console.log('[post-build] runtime-config.js <- SYNCFUSION_LICENSE_KEY (env)');
} else if (existsSync(CAPTURE_FILE)) {
  // (b) Captura del prebuild (la clave que el entrypoint del contenedor
  //     inyectó en el último arranque) → se conserva a través del rebuild.
  copyFileSync(CAPTURE_FILE, DIST_CONFIG);
  rmSync(CAPTURE_FILE, { force: true });
  console.log('[post-build] runtime-config.js <- captura del prebuild (conserva clave del contenedor)');
} else {
  // (c) Placeholder público (clave vacía) → fuente de verdad local.
  if (!existsSync(PUBLIC_CONFIG)) {
    fail(`no existe ${PUBLIC_CONFIG} (ni SYNCFUSION_LICENSE_KEY env ni captura previa).`);
  }
  copyFileSync(PUBLIC_CONFIG, DIST_CONFIG);
  console.log(`[post-build] runtime-config.js <- ${PUBLIC_CONFIG}`);
}

console.log('[post-build] OK');
