"""Pydantic models for the In-Stay (Mi Estancia) module."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from pydantic import BaseModel, Field


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


# ── Stay Session (generated by staff, embedded in QR code) ──


class StaySessionCreate(BaseModel):
    booking_id: str
    prop_id: int
    room_label: str
    guest_name: str
    check_in: str
    check_out: str
    expires_at: datetime | None = None


class StaySessionResponse(BaseModel):
    token: str
    booking_id: str
    prop_id: int
    room_label: str
    guest_name: str
    check_in: str
    check_out: str
    created_at: str
    expires_at: str | None = None
    active: bool = True


# ── Service Requests ──

SERVICE_REQUEST_TYPES = {
    "housekeeping": "Limpieza de habitación",
    "towels": "Toallas adicionales",
    "amenities": "Amenities (jabón, shampoo, etc.)",
    "maintenance": "Mantenimiento (avería en habitación)",
    "room_service": "Servicio a la habitación",
    "minibar": "Minibar",
    "laundry": "Lavandería / Tintorería",
    "wake_up_call": "Llamada de despertar",
    "late_checkout": "Late check-out",
    "extra_bed": "Cama adicional",
    "spa": "Spa & Bienestar",
    "restaurant": "Reserva en restaurante",
    "extend_stay": "Extender estancia",
    "early_checkout": "Salida anticipada",
    "other": "Otro",
}

SERVICE_REQUEST_STATUSES = {
    "pending": "Pendiente",
    "in_progress": "En proceso",
    "completed": "Completado",
    "cancelled": "Cancelado",
}


class ServiceRequestCreate(BaseModel):
    booking_id: str
    prop_id: int
    room_label: str
    request_type: str = "other"
    description: str = ""


class ServiceRequestResponse(BaseModel):
    id: str = Field(alias="_id")
    booking_id: str
    prop_id: int
    room_label: str
    request_type: str
    request_type_label: str = ""
    description: str
    status: str = "pending"
    status_label: str = "Pendiente"
    staff_response: str = ""
    created_at: str
    resolved_at: str | None = None


class ServiceRequestUpdate(BaseModel):
    status: str = "in_progress"
    staff_response: str = ""


# ── Chat Messages ──


class ChatMessageCreate(BaseModel):
    booking_id: str
    prop_id: int
    room_label: str
    sender: str = "guest"  # guest | staff
    staff_name: str = ""
    message: str


class ChatMessageResponse(BaseModel):
    id: str = Field(alias="_id")
    booking_id: str
    prop_id: int
    room_label: str
    sender: str
    staff_name: str = ""
    message: str
    created_at: str
    read: bool = False


# ── Portal Data (compendium + booking summary) ──


class CompendiumInfo(BaseModel):
    hotel_name: str = ""
    hotel_address: str = ""
    hotel_phone: str = ""
    wifi_ssid: str = ""
    wifi_password: str = ""
    check_in_time: str = "15:00"
    check_out_time: str = "12:00"
    breakfast_hours: str = ""
    restaurant_hours: str = ""
    gym_hours: str = ""
    pool_hours: str = ""
    parking_info: str = ""
    emergency_contact: str = ""
    policies: list[dict[str, Any]] = []
    amenities: list[dict[str, Any]] = []


class PortalData(BaseModel):
    session: StaySessionResponse
    compendium: CompendiumInfo
    charges: list[dict[str, Any]] = []
    unread_messages: int = 0
    pending_requests: int = 0
