"""Apply deterministic Punto 1 financial/operational repairs.

The migration intentionally does not resolve ambiguous historical balances,
refund targets, maintenance costs, or folio ownership. Those remain findings
for an explicit operator decision. The two repairs here are deterministic:

* positive guest invoices with no invoice-origin ledger rows get the canonical
  double-entry rows generated by the existing ledger hook;
* legacy ``room_status_log.status == occupied`` is normalized to
  ``occupied_clean`` while preserving the original value in metadata.

Both operations are idempotent and can be previewed with ``--dry-run``.
"""
from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.app.modules.expenses.service.ledger_hooks import generate_ledger_from_invoice
from src.database.connection import get_database

MIGRATION_ID = "punto1-financial-reconciliation-20260807"


def migrate_invoice_ledger(db, *, prop_id: int | None = None, apply: bool = False) -> dict[str, Any]:
    """Repair positive guest invoices that have no invoice ledger source."""
    # Cancelled/refunded invoices are not active receivables. Their ledger
    # history must be handled by an explicit reversal workflow, never by this
    # positive-total backfill.
    query: dict[str, Any] = {
        "total": {"$gt": 0},
        "status": {"$nin": ["cancelled", "refunded"]},
    }
    if prop_id is not None:
        query["prop_id"] = prop_id

    scanned = 0
    candidates = 0
    repaired = 0
    skipped = 0
    rows: list[dict[str, Any]] = []
    for invoice in db.reservation_invoices.find(query).sort("_id", 1):
        scanned += 1
        invoice_number = str(invoice.get("invoice_number") or "")
        if not invoice_number:
            skipped += 1
            continue
        existing_rows = list(db.ledger_transactions.find({
            "prop_id": invoice.get("prop_id"),
            "source": "invoice",
            "source_id": invoice_number,
        }, {"debit": 1, "credit": 1}))
        debit = round(sum(float(row.get("debit", 0) or 0) for row in existing_rows), 2)
        credit = round(sum(float(row.get("credit", 0) or 0) for row in existing_rows), 2)
        # A balanced source is complete. A partial/unbalanced source is also
        # a deterministic repair candidate: the idempotent hook first needs to
        # remove the incomplete pair before rebuilding it.
        if len(existing_rows) >= 2 and debit > 0 and debit == credit:
            continue
        candidates += 1
        row = {"invoice_id": str(invoice["_id"]), "invoice_number": invoice_number, "total": invoice.get("total", 0)}
        if apply:
            if existing_rows:
                db.ledger_transactions.delete_many({
                    "prop_id": invoice.get("prop_id"),
                    "source": "invoice",
                    "source_id": invoice_number,
                })
            created = generate_ledger_from_invoice(invoice, db=db)
            if created:
                now = datetime.now(timezone.utc)
                db.reservation_invoices.update_one(
                    {"_id": invoice["_id"]},
                    {"$set": {
                        "metadata.migration_id": MIGRATION_ID,
                        "metadata.repaired_at": now,
                        "metadata.repair": "invoice_ledger_backfill",
                    }},
                )
                repaired += 1
                row["ledger_rows_created"] = created
            else:
                skipped += 1
        else:
            repaired += 1
            row["ledger_rows_created"] = "would_generate"
        rows.append(row)

    return {
        "apply": apply,
        "migration_id": MIGRATION_ID,
        "prop_id": prop_id,
        "scanned": scanned,
        "candidates": candidates,
        "repaired": repaired,
        "skipped": skipped,
        "rows": rows,
    }


def normalize_room_statuses(db, *, prop_id: int | None = None, apply: bool = False) -> dict[str, Any]:
    """Normalize legacy room statuses while retaining an audit copy."""
    query: dict[str, Any] = {"status": "occupied"}
    if prop_id is not None:
        query["prop_id"] = prop_id

    scanned = 0
    updated = 0
    rows: list[str] = []
    for doc in db.room_status_log.find(query).sort("_id", 1):
        scanned += 1
        updated += 1
        rows.append(str(doc["_id"]))
        if apply:
            now = datetime.now(timezone.utc)
            db.room_status_log.update_one(
                {"_id": doc["_id"], "status": "occupied"},
                {"$set": {
                    "status": "occupied_clean",
                    "metadata.original_status": "occupied",
                    "metadata.migration_id": MIGRATION_ID,
                    "metadata.normalized_at": now,
                    "updated_at": now,
                }},
            )

    return {
        "apply": apply,
        "migration_id": MIGRATION_ID,
        "prop_id": prop_id,
        "scanned": scanned,
        "updated": updated,
        "rows": rows,
    }


def mark_unposted_charges(db, *, prop_id: int | None = None, apply: bool = False) -> dict[str, Any]:
    """Classify charges with no matching folio posting; never invent revenue."""
    query: dict[str, Any] = {
        "$or": [
            {"posting_status": {"$exists": False}},
            {"posting_status": None},
            {"posting_status": ""},
            {"posting_status": "pending"},
        ],
    }
    if prop_id is not None:
        query["prop_id"] = prop_id
    scanned = 0
    updated = 0
    for charge in db.additional_charges.find(query).sort("_id", 1):
        scanned += 1
        booking_id = charge.get("booking_id")
        folio = db.guest_folios.find_one({"prop_id": charge.get("prop_id"), "booking_id": booking_id}, {"postings": 1})
        charge_id = str(charge["_id"])
        posted = any(str(posting.get("reference_id")) == charge_id for posting in (folio or {}).get("postings", []))
        if posted:
            continue
        if apply:
            db.additional_charges.update_one(
                {"_id": charge["_id"], "$or": [
                    {"posting_status": {"$exists": False}},
                    {"posting_status": None},
                    {"posting_status": ""},
                    {"posting_status": "pending"},
                ]},
                {"$set": {
                    "posting_status": "posting_failed",
                    "posting_error": "migration: no folio posting found",
                    "metadata.migration_id": MIGRATION_ID,
                }},
            )
        updated += 1
    return {"apply": apply, "migration_id": MIGRATION_ID, "prop_id": prop_id, "scanned": scanned, "updated": updated}


def recover_stuck_charges(db, *, prop_id: int | None = None, apply: bool = False) -> dict[str, Any]:
    """Finalize only charges whose stable reversal/replacement already exists.

    This is deterministic crash recovery: it never creates a missing posting,
    changes an amount, or guesses whether a partial edit should win.
    """
    from src.app.modules.housekeeping.service.lifecycle.charges import recover_additional_charge

    query: dict[str, Any] = {"posting_status": {"$in": ["reversing", "updating"]}}
    if prop_id is not None:
        query["prop_id"] = prop_id
    scanned = recovered = skipped = 0
    rows: list[dict[str, Any]] = []
    for charge in db.additional_charges.find(query).sort("_id", 1):
        scanned += 1
        row = {"charge_id": str(charge["_id"]), "posting_status": charge.get("posting_status")}
        if apply:
            result = recover_additional_charge(str(charge["_id"]), db=db)
            if result and result.get("posting_status") in {"reversed", "posted"}:
                recovered += 1
                row["result"] = result.get("posting_status")
            else:
                skipped += 1
        else:
            skipped += 1
            row["result"] = "would_attempt_recovery"
        rows.append(row)
    return {
        "apply": apply,
        "migration_id": MIGRATION_ID,
        "prop_id": prop_id,
        "scanned": scanned,
        "recovered": recovered,
        "skipped": skipped,
        "rows": rows,
    }


def migrate(*, prop_id: int | None = None, apply: bool = False) -> dict[str, Any]:
    db = get_database()
    return {
        "invoice_ledger": migrate_invoice_ledger(db, prop_id=prop_id, apply=apply),
        "room_statuses": normalize_room_statuses(db, prop_id=prop_id, apply=apply),
        "unposted_charges": mark_unposted_charges(db, prop_id=prop_id, apply=apply),
        "stuck_charges": recover_stuck_charges(db, prop_id=prop_id, apply=apply),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Apply deterministic Punto 1 repairs")
    parser.add_argument("--prop-id", type=int, default=None)
    parser.add_argument("--dry-run", action="store_true", help="Preview changes without writing")
    parser.add_argument("--apply", action="store_true", help="Persist deterministic repairs")
    args = parser.parse_args()
    if args.dry_run and args.apply:
        parser.error("--dry-run y --apply son mutuamente excluyentes")
    result = migrate(prop_id=args.prop_id, apply=args.apply)
    print(result)


if __name__ == "__main__":
    main()
